# Generated by Django 4.2 on 2023-08-09 04:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imagerie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("categorie", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "date_image",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 8, 9, 4, 55, 13, 847635)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personne",
            fields=[
                ("personneID", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=200)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "masculin"), ("F", "féminin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField()),
                (
                    "mere",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnes_mere",
                        to="image_app.personne",
                    ),
                ),
                (
                    "pere",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personnes_pere",
                        to="image_app.personne",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "personne_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="image_app.personne",
                    ),
                ),
                (
                    "agentID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matricule", models.CharField(max_length=6, null=True)),
            ],
            bases=("image_app.personne",),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "personne_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="image_app.personne",
                    ),
                ),
                (
                    "patientID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_accueil", models.DateTimeField(auto_now=True)),
                ("contact", models.CharField(max_length=9, null=True)),
            ],
            bases=("image_app.personne",),
        ),
        migrations.CreateModel(
            name="Resultats",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("result", models.TextField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_app.imagerie",
                    ),
                ),
                (
                    "interpreteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_app.agent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="imagerie",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="image_app.patient"
            ),
        ),
        migrations.AddField(
            model_name="imagerie",
            name="technicien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="image_app.agent"
            ),
        ),
    ]
