# Generated by Django 4.2 on 2023-08-09 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_app", "0004_alter_imagerie_date_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagerie",
            name="date_image",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 9, 5, 7, 49, 185333)
            ),
        ),
    ]
