# Generated by Django 4.2 on 2023-08-09 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_app", "0009_alter_imagerie_date_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagerie",
            name="date_image",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 9, 6, 53, 44, 919568)
            ),
        ),
    ]
